public/dq.js
Noticed some 'expected a number' errors in console but the chart is displaying correctly
=> Format dates in date chart

public/dq.js
- Deepcopy of store items before pushing to combined store, to preserve originals
=> Deepcopy of store items

public/dq.js
- Added DQ metric for URL counts. This is the number of items with data.eventSchedule.urlTemplate plus the number of unique data.url values for the items with no data.eventSchedule.urlTemplate.
- Fixed a bug in the geo check
- Fixed log messages about dates
=> Added DQ metric for URL counts

public/apisearch.js, public/dq.js
- Allowed data quality to be determined from a single store if combined store cannot be created
- Improved handling of feed linking variable, ensuring that it doesn't depend on feed ingress order
=> Allowed data quality to be determined from a single store

public/apisearch.js, public/dq.js
- Modified labels to be conditional depending on super-event type and sub-event type
=> Conditional labels

public/apisearch.js, public/dq.js
- Reverted focus from feedType to ingressOrder, as we don't always know feedType but we do always know ingressOrder, even though the former is more meaningful but we're working with whatever data providers have done
- Ensured that a feed can still be processed even if it doesn't have a feedType. In this case, we can try to make some decisions regarding the content type based on itemDataType instead.
- Added store.itemKind just to observe for now, not currently used
- Added some protection against storeIngressOrder1.firstPage and storeIngressOrder2.firstPage being the same
=> Handle undefined feedType

public/apisearch.js, public/dq.js, public/index.html, public/style.css
Single feeds like SportSuite still need some refining.
=> Improved display of json (still to do SportSuite)

public/apisearch.js, public/dq.js, public/index.html
- Updated output JSON handling
- Ensured that the JSON tab is always available, with the first results item being the first selected for the JSON tab. Also works when results are filtered.
- Modified the JSON button in the results tab to be highlighted when the results item is present in the JSON tab
- Added location name to the results tab if it is buried in superEvent info
- Added header row to the results tab
=> Updated output JSON handling

public/apisearch.js, public/dq.js, public/index.html, public/style.css
- Fixed a bug with the organiser and location lists not properly updating upon filter
- Updated filter list functions, stopping them from triggering if the new selection is the same as the last selection
- Updated nomenclature for filter list selections for clarity and consistency
- Updated HTML and CSS for tweaked layout
=> Enhanced filter list handling

public/apisearch.js, public/index.html
- Allowed users to provide their own ingress-order-1 feed URL, from which the ingress-order-2 feed URL is inferred if possible
- Refactored initial store setup operations into their own functions, which further simplifies runForm()
- Added clearing function for global variables
=> Allowed users to provide their own ingress-order-1 feed URL

public/apisearch.js, public/dq.js, public/style.css
- Added an object to store the RPDE URL for each feed item
- Added a button to take the user from item JSON to its raw source page in the RPDE feed. Note that this still requires work as it can be hampered by caching.
- Changed Object.values to Object.keys when only using for length. May have a small memory saving.
=> Button from item JSON to RPDE source. Still issue with cache though.

app.js, public/apisearch.js
- Disabled client-side caching
- Added server-side cache monitoring endpoints
=> Cache adjustments

public/apisearch.js, public/dq.js
- Fixed a bug whereby the activity dropdown list wasn't showing. This was because the activity prefLabels were being passed to generateSubset() instead of the activity IDs.
- Fixed a bug whereby the activity dropdown list wasn't showing as an indented hierarchy. This was due to a CSS class which had gone astray.
=> Fix activity dropdown

app.js
- Modified server to allow access control from any origin i.e. any client. This is Cross Origin Request Security (CORS) policy, see here for details: https://www.w3.org/wiki/CORS_Enabled.
=> Cross Origin Request Security (CORS) policy

app.js, public/apisearch.js
- Modified retry code to allow for 3 auto-retries per page, but still unlimited retries per feed
- Tweaked app.js with just some commented stuff on CORS, plus an indent
=> Update retry code

public/apisearch.js, public/dq.js
- Ensured that a superEvent feed can be the basis of the data quality metrics. Previously it was largely assumed that this would be a subEvent feed.
- Added setStoreSuperEventAndStoreSubEvent() function to determine storeSuperEvent and storeSubEvent only after the full RPDE read, so allowing for use of feedType and then itemDataType as necessary in the same section. This involved some refactoring.
- Added an explicit 'eventType' property to the stores (taking a value of 'superEvent' or 'subEvent'), similar to how we have an explicit 'ingressOrder' property
- Modified setJSONTab() to accommodate various scenarios
=> Ensured that a superEvent feed can be the basis of the data quality metrics

public/apisearch.js, public/dq.js
- Added more flexibility to the determination of storeSuperEvent and storeSubEvent, now assessing storeIngressOrder2 if can't be determined from storeIngressOrder1
- Added more flexibility to the determination of storeIngressOrder2.firstPage and the feed linking variable, now allowing for various forms of content type labels
- Merged handling of facilityUse and individualFacilityUse
=> Store info flexibility

public/dq.js
- Allowed storeIngressOrder1 or storeIngressOrder2 to pass through to final DQ metrics stage even if eventType (superEvent or subEvent) cannot be determined
- Removed record of item indices associated with a given parent from the raw data, as this was apparent in front-end JSON view in cases when we don't have a separate copy of the raw data
=> Allowed undefined feed types to pass through to final DQ metrics stage

public/apisearch.js, public/dq.js
- Modified overall execution flow and flags, including disabling and enabling of control buttons at various points
- Modified stop triggered by user, causing it to throw an error which is then caught at any stage and handled to bring things to a halt and then clear. The new try-catch blocks should also then help with other errors too.
- Modified clearDisplay() to better handle various page elements
- Modified clearGlobals() to better reset to a basic state for a new run
- Removed runForm() and put content into execute()
- Removed loadingTakingTime() and put directly into loadingStart() as an anonymous function
=> Modified overall execution flow, including forced stop while in progress

public/apisearch.js, public/dq.js, public/style.css
- Modified list of API calls to be links
- Modified colours of API calls and buttons
- Moved clearTimeout() from stop() to immediately when stop is triggered, otherwise it could have appeared when stopping was occurring
- Enabled clear button for sample feed as well as other feeds, as needed to clear filters
=> API call links and colours

public/index.html, public/style.css
- Added a container for in-browser log messages, with a capped height but scroll in the y-direction
- Ensured whole page prioritises scroll in the y-direction
- Modified toggle colours to match buttons
=> Browser log scroll

public/apisearch.js
- Added ability to use non-standard URLs e.g. those that begin '/api' or '%2Fapi' and which are designed to work as a suffix to a base part, or those which are already encoded
- Added fix to JSON display, which wasn't previously showing anything if we hadn't determined storeSuperEvent and store storeSubEvent
=> Allowed non standard URLs, and fixed a JSON display bug

public/apisearch.js, public/dq.js
- Added more options for locationName, allowing for items that don't have an actual location.name field, which then allows for them in the location list and on the map
- Added DQ_validCoords and DQ_validPostalCode, which together define DQ_validGeo. It is useful to have the former two separately.
- Added protection against missing startDate
- Added all numFilteredItemsWith... counts into storeDataQuality for consistency
- Added hidden filters to clearFilters() for consistency
- Removed or commented superfluous functions and variables
- Reduced repetition of same/similar calculations to streamline
- Renamed and reordered throughout for clarity and consistency
- Replaced DQ_validOrganizer with organizerName. The flag wasn't being used, but the name is useful to store.
- Replaced …
=> Allow more location variants

public/apisearch.js, public/dq.js, public/index.html, public/style.css
- Added process for user-facing messages, with an echo feature to print the same to the dev log if desired
- Added persistent progress indicator that can simply be shown/hidden as needed, rather than added/destroyed as previously
- Modified HTML and CSS to accommodate new user-facing messages, and then for general consistency and style. Everything above the DQ metrics is now properly reactive to flow/collapse depending on device size, and some changes made to DQ metrics to move in this direction too.
- Modified measurement of time taken to ensure it starts just when the loading process starts
- Modified retry process, now capturing current URL and store each time the loading loop is entered, added some helper functions, added better clearing of retry variables
- Modified API tab item …
=> Added process for user-facing messages. Updated retry. Updated appearance.

app.js
- Added server-side retry functionality for the axios.get() calls to the catalogue collection, catalogues and datasets. Previously a number of datasets were missed out on even though they were actually available, just needed one or two retries due to server errors.
- Added protection against missing content in raw dataset info
- Modified server-side feed filtering to match the current downstream essentials
=> Retry server calls on initial load if errors encountered

app.js
- Restructured server-side code, grouping together like code and improving the ordering for readability. Some light renaming and tweaks woven in. Looks like a lot of changes, but it's mostly just blocks of code shifted around.
- Refactored functions to run on load into the app.listen() callback
- Refactored common SQL queries to their own functions
- Removed duplicate wait/sleep function
=> Restructured server-side code
